### ISSUE TITLE
wikitravel.org

### ISSUE THREAD

**Issue by alexeydg** [dmitry-ivanov/laravel-wikipedia-grabber#11]
do you add parsing https://wikitravel.org ?

**Comment by dmitry-ivanov** [comment]
If it uses [MediaWiki](https://www.mediawiki.org/wiki/MediaWiki) under the hood, then it should work.

Just use the `MediaWiki` class as [readme suggests](https://github.com/dmitry-ivanov/laravel-wikipedia-grabber#mediawiki).

Please note, that you should specify the correct URL to the API entry point as the first argument:

```php
use MediaWiki;

echo (new MediaWiki('https://wikitravel.org/set/the/corrent/path/to/api.php'))
    ->page('Donald Trump');
```
