### ISSUE TITLE
bug parse wikitravel

### ISSUE THREAD

**Issue by alexeydg** [dmitry-ivanov/laravel-wikipedia-grabber#12]
`echo (new MediaWiki('http://wikitravel.org/wiki/en/api.php'))
    ->page('Samara')->bootstrap();`

  ErrorException  : Undefined index: extract

  at /home/vagrant/code/vendor/illuminated/wikipedia-grabber/src/Grabber/EntitySingular.php:129
    125|             }
    126|
    127|             $isPreview = !empty($this->response['iwg_preview']);
    128|
  > 129|             $this->parser = new Parser($this->getTitle(), $this->response['extract'], $imagesResponseData, $isPreview);
    130|         }
    131|
    132|         return $this->parser;
    133|     }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: extract", "/home/vagrant/code/vendor/illuminated/wikipedia-grabber/src/Grabber/EntitySingular.php", [])
      /home/vagrant/code/vendor/illuminated/wikipedia-grabber/src/Grabber/EntitySingular.php:129

  2   Illuminated\Wikipedia\Grabber\EntitySingular::getParser()
      /home/vagrant/code/vendor/illuminated/wikipedia-grabber/src/Grabber/EntitySingular.php:88

**Comment by dmitry-ivanov** [comment]
It seems like "wikitravel.org" response doesn't match expected, as it comes from Wikipedia's MediaWiki.

Sorry, but I don't have time for that now.

Feel free to open PR if you find a solution.
