### ISSUE TITLE
Random page

### ISSUE THREAD

**Issue by railken** [dmitry-ivanov/laravel-wikipedia-grabber#4]
Hi,

Wikipedia offers the possibility to get a random page

`https://en.wikipedia.org/w/api.php?action=query&list=random&format=json&rnnamespace=0&rnlimit=10`

Do you have any plans to add this feature?

**Comment by dmitry-ivanov** [comment]
Hi, @railken !

I didn't have such plans, however, I think I can add this feature.

Thanks for your idea!

**Comment by dmitry-ivanov** [comment]
Done and released:
https://github.com/dmitry-ivanov/laravel-wikipedia-grabber/releases/tag/5.6.3

Thanks!

**Comment by dmitry-ivanov** [comment]
Hey, @railken !

Please, note that I've decided to rename it from `random` => `randomPage` to make it more clear:
https://github.com/dmitry-ivanov/laravel-wikipedia-grabber/releases/tag/5.6.4

Thanks!
