### ISSUE TITLE
access api error readapidenied ?

### ISSUE THREAD

**Issue by ardyanto** [dmitry-ivanov/laravel-wikipedia-grabber#6]
i got error when i call api media wiki 

"error" => array:3 [▼
    "code" => "readapidenied"
    "info" => "You need read permission to use this module"
    "docref" => "See http://accpedia.acc.co.id/glossary/api.php for API usage"
  ]

Please how to fix ..

Thank youu ..

**Comment by dmitry-ivanov** [comment]
Please, provide the code you're using.
