### ISSUE TITLE
How to get infobox / vcard data?

### ISSUE THREAD

**Issue by sclrship** [dmitry-ivanov/laravel-wikipedia-grabber#8]
I am curious to know how to get infobox / vcard data of any page. For example, I want to access birthday from vcard data.

<img width="290" alt="Screenshot 2019-05-03 at 4 14 17 PM" src="https://user-images.githubusercontent.com/50169356/57131608-b89cac00-6dbe-11e9-949b-af3fd09972b2.png">

**Comment by dmitry-ivanov** [comment]
You can't do it using this package.

Probably you should check [MediaWiki API](https://www.mediawiki.org/wiki/API:Main_page) for that.
